# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6d4b494350a333621556594232216faed8c194c51169db4516188ad0e114e2f9d707db95c1fe525b497cb254f6b552301656716a8dadc87d2f7fd40901bca45

test:
  secret_key_base: e23a31c5fab3da3c6a7f6a7c6e305e7f86ad0883d608fd1c612b9aa6c46a7f4a6daeea29056392fbf34e4531d1da936a1ed6136d568e3e067d8fefb9c3d2d938

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
